apiVersion: v1
kind: Service
metadata:
  name: simple-app.service
  namespace: simple-app-ns
  labels:
    service-name: simple-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
  selector:
    pod-name: simple-app-pod