kind: Namespace
apiVersion: v1
metadata:
  name: simple-app-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: simple-app-ns
  name: simple-app-deployment
  labels:
    dep-name: simple-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      namespace: simple-app-ns
      name: simple-app-pod
      labels:
        pod-name: simple-app-pod
    spec:
      containers:
        - name: simple-app
          image: mainul35/simple-app:1.1
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      pod-name: simple-app-pod
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace: simple-app-ns
  labels:
    service-name: simple-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
  selector:
    pod-name: simple-app-pod