apiVersion: v1
kind: Service
metadata:
  name: article-db-service
  namespace: dev
spec:
  selector:
    app-name: article-db
    type: pod  # Service communicates to the POD directly
  ports:
    - protocol: TCP
      port: 3222
      targetPort: 5432
#      nodePort: 32222
  type: LoadBalancer   # Change to NodePort or LoadBalancer if needed
