apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql_db_pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: psql_db
  labels:
    db_name: article_db
spec:
  containers:
    - name: psql_container
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: article_db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: secret
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: psql_db_volume
  volumes:
    - name: psql_db_volume
      persistentVolumeClaim:
        claimName: psql_db_pvc